spring:
  application:
    name: jtim-logic-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    hikari:
      maximum-pool-size: 50
      idle-timeout: 30000
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/jtim?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai

## dubbo config
dubbo:
  scan:
    base-packages: cn.bytes.jtim.logic.service.rpc
  protocol:
    port: -1
    name: dubbo
    provider:
      filter: dubboExceptionFileter
  registry:
    protocol: zookeeper
    address: 127.0.0.1:2182

## mybatis config
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
  type-enums-package:
  type-aliases-package: com.bytes.jtim.logic.domain
